#!/bin/bash
CROSS_COMPILE_PATH=/usr/bin
make -j10 KDEB_PKGVERSION=21.08.0-trunk BRANCH=edge LOCALVERSION=-sun50iw11 KBUILD_DEBARCH=arm64 ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE_PATH/aarch64-linux-gnu-
